package packageCA_Event;

import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.io.IOException;  // Import the IOException class to handle errors

public class ClassCA_Event  {
	
	public  void methodCA_EVENT(String Arg_DB_endpoint,String Arg_port,String Arg_DB_SID,String Arg_DB_uname,String Arg_DB_password,String Arg_Event_num) throws SQLException, IOException{
		
	
	
	 String DB_endpoint= Arg_DB_endpoint;
     String port= Arg_port;
     String DB_SID= Arg_DB_SID;
     String DB_uname= Arg_DB_uname;
     String DB_password= Arg_DB_password;
     String Event_num = Arg_Event_num;
     
     String sql   = "select  ACTIVE_STATUS,APPROVAL_STATUS,ARCHIVAL_STATUS,ASSET_ID,ASSET_IDENTIFIERS,BUYA_CONFIRMED_STATUS,BUYA_DEPOSITED_STATUS,CA_ACCOUNT_REFERENCE,CA_REFERENCE,CA_SENDER_REFERENCE,CA_SOURCE_RULE,CLEANSE_BY_DATE,CLEANSING_RANK,CLEANSING_STATUS,CLOSED_DT,COMMON_GROUPING_ATT,COMMUNICATION_STATUS,COMPLETENESS_STATUS,CONTINUATION_INDICATOR,CRITICAL_DATE,DATA_SOURCE,DEFAULT_OPTION_STATUS,DEPOSITED_STATUS,DEPOSIT_CONFIRMED_STATUS,DETAIL_COMPLETENESS_STATUS,ELECTION_REC_FLAG,ELECTION_REC_STATUS,ELECTION_STATUS,ELGBLTY_IND,ELGBL_BAL_IND,ELIGIBLE_POSITIONS_REQ_STATUS,ENTITLEMENT_REC_FLAG,ENTITLEMENT_REC_STATUS,ENTITLEMENT_STATUS,ENTITY_TYPE,EVENT_FUNCTION,EVENT_NUM,EVENT_TYPE,EVT_CMPLTNS_STS,EVT_CONF_STS,FLOW_ID,FORECAST_CONFIRMATION_STRATEGY,FORECAST_STATUS,GOLDEN_RECORD_FLAG,HAS_NARRATIVE,HAS_OPTION,INBOX_ID,INTERNAL_DEADLINE_DATE,INTERNAL_DEADLINE_DISPLAY,INTERNAL_DEADLINE_FORMAT_TYPE,INTERNAL_DEADLINE_TIMEZONE,IS_LATEST_SUMMARY,IS_OUTCOME_BLOCKING_ACTIVE,IS_TRADE_BLOCKING_ACTIVE,LAST_ACTION_DATE,LAST_ACTION_ID,LAST_ACTION_OWNER,LINKED_EVENT_NUM,LISTING_ID,LOAD_FAILURE_CODE,LOAD_FAILURE_REVIEWED,MANDATORY_OPTIONS,MAND_VOLU_INDICATOR,MASTER_ID,MASTER_RECORD_LOCK,MINIMUM_SOURCE_STATUS,MIN_NO_OF_OPTIONS,NARRATIVE_LOCK_STATUS,NEXT_REVIEW_DATE,NOTE_ID,OFFEROR,OPTION_CLEANSING_STATUS,OPTION_COMPLETENESS_STATUS,OUTCOME_BLOCKING_STATUS,OVERALL_STATUS,PAGE_NUMBER,POSITION_REC_FLAG,POSITION_REC_STATUS,PREPARATION_DT,PRIORITY,PROCESSING_STATUS,PROCESSING_TYPE,READY_FOR_ARCHIVAL_DATE,READ_STATUS,RECONCILIATION_STATUS,RECORD_TYPE,REC_EVENT_CONFIG_ID,RESPONSIBLE_PARTY,RESP_PARTY_MANUAL_CHANGE,RVSL_RSN,SETTLED_LOCK_IN_DATE,SETTLED_LOCK_IN_DATE_ATT_ID,SETTLED_LOCK_IN_OFFSET,SETTLED_OPTION_SEQ_NUM,SETTLED_TERM_SEQ_NUM,SLLE_CONFIRMED_STATUS,SLLE_DEPOSITED_STATUS,SOFT_LOCK_KEY,SOURCE_COMPLETENESS_STATUS,STATUS,SUB_FUNCTION,SYS_ENTRY_DATE,TRADED_LOCK_IN_DATE,TRADED_LOCK_IN_DATE_ATT_ID,TRADED_LOCK_IN_OFFSET,TRADED_OPTION_SEQ_NUM,TRADED_TERM_SEQ_NUM,TRADE_BLOCKING_STATUS,USER_ID,VOTING_FORM_COMPLETE_STATUS,VOTING_STATUS  from ca_event where event_num in (select event_num from ca_Event where master_id in ( Select master_id from ca_event where event_num='"+Event_num+"'))" ;
     
         
     
     // Get SQL from the flat file named "sqlfile"
     System.out.println(sql);
       
     try {
     	Class.forName("oracle.jdbc.driver.OracleDriver");
		} catch (ClassNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
		} 
     
     FileWriter myWriter;
		myWriter = new FileWriter(System.getProperty("user.dir")+"\\"+Event_num+"CA_Event.csv");
		myWriter.write("ACTIVE_STATUS,APPROVAL_STATUS,ARCHIVAL_STATUS,ASSET_ID,ASSET_IDENTIFIERS,BUYA_CONFIRMED_STATUS,BUYA_DEPOSITED_STATUS,CA_ACCOUNT_REFERENCE,CA_REFERENCE,CA_SENDER_REFERENCE,CA_SOURCE_RULE,CLEANSE_BY_DATE,CLEANSING_RANK,CLEANSING_STATUS,CLOSED_DT,COMMON_GROUPING_ATT,COMMUNICATION_STATUS,COMPLETENESS_STATUS,CONTINUATION_INDICATOR,CRITICAL_DATE,DATA_SOURCE,DEFAULT_OPTION_STATUS,DEPOSITED_STATUS,DEPOSIT_CONFIRMED_STATUS,DETAIL_COMPLETENESS_STATUS,ELECTION_REC_FLAG,ELECTION_REC_STATUS,ELECTION_STATUS,ELGBLTY_IND,ELGBL_BAL_IND,ELIGIBLE_POSITIONS_REQ_STATUS,ENTITLEMENT_REC_FLAG,ENTITLEMENT_REC_STATUS,ENTITLEMENT_STATUS,ENTITY_TYPE,EVENT_FUNCTION,EVENT_NUM,EVENT_TYPE,EVT_CMPLTNS_STS,EVT_CONF_STS,FLOW_ID,FORECAST_CONFIRMATION_STRATEGY,FORECAST_STATUS,GOLDEN_RECORD_FLAG,HAS_NARRATIVE,HAS_OPTION,INBOX_ID,INTERNAL_DEADLINE_DATE,INTERNAL_DEADLINE_DISPLAY,INTERNAL_DEADLINE_FORMAT_TYPE,INTERNAL_DEADLINE_TIMEZONE,IS_LATEST_SUMMARY,IS_OUTCOME_BLOCKING_ACTIVE,IS_TRADE_BLOCKING_ACTIVE,LAST_ACTION_DATE,LAST_ACTION_ID,LAST_ACTION_OWNER,LINKED_EVENT_NUM,LISTING_ID,LOAD_FAILURE_CODE,LOAD_FAILURE_REVIEWED,MANDATORY_OPTIONS,MAND_VOLU_INDICATOR,MASTER_ID,MASTER_RECORD_LOCK,MINIMUM_SOURCE_STATUS,MIN_NO_OF_OPTIONS,NARRATIVE_LOCK_STATUS,NEXT_REVIEW_DATE,NOTE_ID,OFFEROR,OPTION_CLEANSING_STATUS,OPTION_COMPLETENESS_STATUS,OUTCOME_BLOCKING_STATUS,OVERALL_STATUS,PAGE_NUMBER,POSITION_REC_FLAG,POSITION_REC_STATUS,PREPARATION_DT,PRIORITY,PROCESSING_STATUS,PROCESSING_TYPE,READY_FOR_ARCHIVAL_DATE,READ_STATUS,RECONCILIATION_STATUS,RECORD_TYPE,REC_EVENT_CONFIG_ID,RESPONSIBLE_PARTY,RESP_PARTY_MANUAL_CHANGE,RVSL_RSN,SETTLED_LOCK_IN_DATE,SETTLED_LOCK_IN_DATE_ATT_ID,SETTLED_LOCK_IN_OFFSET,SETTLED_OPTION_SEQ_NUM,SETTLED_TERM_SEQ_NUM,SLLE_CONFIRMED_STATUS,SLLE_DEPOSITED_STATUS,SOFT_LOCK_KEY,SOURCE_COMPLETENESS_STATUS,STATUS,SUB_FUNCTION,SYS_ENTRY_DATE,TRADED_LOCK_IN_DATE,TRADED_LOCK_IN_DATE_ATT_ID,TRADED_LOCK_IN_OFFSET,TRADED_OPTION_SEQ_NUM,TRADED_TERM_SEQ_NUM,TRADE_BLOCKING_STATUS,USER_ID,VOTING_FORM_COMPLETE_STATUS,VOTING_STATUS \n");
		
     Connection con = DriverManager.getConnection("jdbc:oracle:thin:@//"+DB_endpoint+":"+port+"/"+DB_SID+"", ""+DB_uname+"", ""+DB_password+""); 
     Statement stmt = con.createStatement(); 
     ResultSet rs = stmt.executeQuery(sql);
    
     while(rs.next()){
         //Retrieve by column name
     int ACTIVE_STATUS =  rs.getInt("ACTIVE_STATUS");
     int APPROVAL_STATUS =  rs.getInt("APPROVAL_STATUS");
     int ARCHIVAL_STATUS =  rs.getInt("ARCHIVAL_STATUS");
     int ASSET_ID =  rs.getInt("ASSET_ID");
     String ASSET_IDENTIFIERS =  rs.getString("ASSET_IDENTIFIERS");
     int BUYA_CONFIRMED_STATUS =  rs.getInt("BUYA_CONFIRMED_STATUS");
     int BUYA_DEPOSITED_STATUS =  rs.getInt("BUYA_DEPOSITED_STATUS");
     String CA_ACCOUNT_REFERENCE =  rs.getString("CA_ACCOUNT_REFERENCE");
     String CA_REFERENCE =  rs.getString("CA_REFERENCE");
     String CA_SENDER_REFERENCE =  rs.getString("CA_SENDER_REFERENCE");
     int CA_SOURCE_RULE =  rs.getInt("CA_SOURCE_RULE");
     String CLEANSE_BY_DATE =  rs.getString("CLEANSE_BY_DATE");
     int CLEANSING_RANK =  rs.getInt("CLEANSING_RANK");
     int CLEANSING_STATUS =  rs.getInt("CLEANSING_STATUS");
     String CLOSED_DT =  rs.getString("CLOSED_DT");
     String COMMON_GROUPING_ATT =  rs.getString("COMMON_GROUPING_ATT");
     int COMMUNICATION_STATUS =  rs.getInt("COMMUNICATION_STATUS");
     int COMPLETENESS_STATUS =  rs.getInt("COMPLETENESS_STATUS");
     int CONTINUATION_INDICATOR =  rs.getInt("CONTINUATION_INDICATOR");
     String CRITICAL_DATE =  rs.getString("CRITICAL_DATE");
     int DATA_SOURCE =  rs.getInt("DATA_SOURCE");
     int DEFAULT_OPTION_STATUS =  rs.getInt("DEFAULT_OPTION_STATUS");
     int DEPOSITED_STATUS =  rs.getInt("DEPOSITED_STATUS");
     int DEPOSIT_CONFIRMED_STATUS =  rs.getInt("DEPOSIT_CONFIRMED_STATUS");
     int DETAIL_COMPLETENESS_STATUS =  rs.getInt("DETAIL_COMPLETENESS_STATUS");
     int ELECTION_REC_FLAG =  rs.getInt("ELECTION_REC_FLAG");
     int ELECTION_REC_STATUS =  rs.getInt("ELECTION_REC_STATUS");
     int ELECTION_STATUS =  rs.getInt("ELECTION_STATUS");
     String ELGBLTY_IND =  rs.getString("ELGBLTY_IND");
     String ELGBL_BAL_IND =  rs.getString("ELGBL_BAL_IND");
     int ELIGIBLE_POSITIONS_REQ_STATUS =  rs.getInt("ELIGIBLE_POSITIONS_REQ_STATUS");
     int ENTITLEMENT_REC_FLAG =  rs.getInt("ENTITLEMENT_REC_FLAG");
     int ENTITLEMENT_REC_STATUS =  rs.getInt("ENTITLEMENT_REC_STATUS");
     int ENTITLEMENT_STATUS =  rs.getInt("ENTITLEMENT_STATUS");
     int ENTITY_TYPE =  rs.getInt("ENTITY_TYPE");
     int EVENT_FUNCTION =  rs.getInt("EVENT_FUNCTION");
     int EVENT_NUM =  rs.getInt("EVENT_NUM");
     int EVENT_TYPE =  rs.getInt("EVENT_TYPE");
     int EVT_CMPLTNS_STS =  rs.getInt("EVT_CMPLTNS_STS");
     int EVT_CONF_STS =  rs.getInt("EVT_CONF_STS");
     int FLOW_ID =  rs.getInt("FLOW_ID");
     int FORECAST_CONFIRMATION_STRATEGY =  rs.getInt("FORECAST_CONFIRMATION_STRATEGY");
     int FORECAST_STATUS =  rs.getInt("FORECAST_STATUS");
     int GOLDEN_RECORD_FLAG =  rs.getInt("GOLDEN_RECORD_FLAG");
     int HAS_NARRATIVE =  rs.getInt("HAS_NARRATIVE");
     int HAS_OPTION =  rs.getInt("HAS_OPTION");
     int INBOX_ID =  rs.getInt("INBOX_ID");
     String INTERNAL_DEADLINE_DATE =  rs.getString("INTERNAL_DEADLINE_DATE");
     String INTERNAL_DEADLINE_DISPLAY =  rs.getString("INTERNAL_DEADLINE_DISPLAY");
     int INTERNAL_DEADLINE_FORMAT_TYPE =  rs.getInt("INTERNAL_DEADLINE_FORMAT_TYPE");
     String INTERNAL_DEADLINE_TIMEZONE =  rs.getString("INTERNAL_DEADLINE_TIMEZONE");
     int IS_LATEST_SUMMARY =  rs.getInt("IS_LATEST_SUMMARY");
     int IS_OUTCOME_BLOCKING_ACTIVE =  rs.getInt("IS_OUTCOME_BLOCKING_ACTIVE");
     int IS_TRADE_BLOCKING_ACTIVE =  rs.getInt("IS_TRADE_BLOCKING_ACTIVE");
     String LAST_ACTION_DATE =  rs.getString("LAST_ACTION_DATE");
     int LAST_ACTION_ID =  rs.getInt("LAST_ACTION_ID");
     String LAST_ACTION_OWNER =  rs.getString("LAST_ACTION_OWNER");
     int LINKED_EVENT_NUM =  rs.getInt("LINKED_EVENT_NUM");
     int LISTING_ID =  rs.getInt("LISTING_ID");
     int LOAD_FAILURE_CODE =  rs.getInt("LOAD_FAILURE_CODE");
     int LOAD_FAILURE_REVIEWED =  rs.getInt("LOAD_FAILURE_REVIEWED");
     int MANDATORY_OPTIONS =  rs.getInt("MANDATORY_OPTIONS");
     int MAND_VOLU_INDICATOR =  rs.getInt("MAND_VOLU_INDICATOR");
     int MASTER_ID =  rs.getInt("MASTER_ID");
     int MASTER_RECORD_LOCK =  rs.getInt("MASTER_RECORD_LOCK");
     int MINIMUM_SOURCE_STATUS =  rs.getInt("MINIMUM_SOURCE_STATUS");
     int MIN_NO_OF_OPTIONS =  rs.getInt("MIN_NO_OF_OPTIONS");
     int NARRATIVE_LOCK_STATUS =  rs.getInt("NARRATIVE_LOCK_STATUS");
     String NEXT_REVIEW_DATE =  rs.getString("NEXT_REVIEW_DATE");
     int NOTE_ID =  rs.getInt("NOTE_ID");
     String OFFEROR =  rs.getString("OFFEROR");
     int OPTION_CLEANSING_STATUS =  rs.getInt("OPTION_CLEANSING_STATUS");
     int OPTION_COMPLETENESS_STATUS =  rs.getInt("OPTION_COMPLETENESS_STATUS");
     int OUTCOME_BLOCKING_STATUS =  rs.getInt("OUTCOME_BLOCKING_STATUS");
     int OVERALL_STATUS =  rs.getInt("OVERALL_STATUS");
     int PAGE_NUMBER =  rs.getInt("PAGE_NUMBER");
     int POSITION_REC_FLAG =  rs.getInt("POSITION_REC_FLAG");
     int POSITION_REC_STATUS =  rs.getInt("POSITION_REC_STATUS");
     String PREPARATION_DT =  rs.getString("PREPARATION_DT");
     int PRIORITY =  rs.getInt("PRIORITY");
     int PROCESSING_STATUS =  rs.getInt("PROCESSING_STATUS");
     int PROCESSING_TYPE =  rs.getInt("PROCESSING_TYPE");
     String READY_FOR_ARCHIVAL_DATE =  rs.getString("READY_FOR_ARCHIVAL_DATE");
     int READ_STATUS =  rs.getInt("READ_STATUS");
     int RECONCILIATION_STATUS =  rs.getInt("RECONCILIATION_STATUS");
     int RECORD_TYPE =  rs.getInt("RECORD_TYPE");
     int REC_EVENT_CONFIG_ID =  rs.getInt("REC_EVENT_CONFIG_ID");
     String RESPONSIBLE_PARTY =  rs.getString("RESPONSIBLE_PARTY");
     int RESP_PARTY_MANUAL_CHANGE =  rs.getInt("RESP_PARTY_MANUAL_CHANGE");
     int RVSL_RSN =  rs.getInt("RVSL_RSN");
     String SETTLED_LOCK_IN_DATE =  rs.getString("SETTLED_LOCK_IN_DATE");
     int SETTLED_LOCK_IN_DATE_ATT_ID =  rs.getInt("SETTLED_LOCK_IN_DATE_ATT_ID");
     int SETTLED_LOCK_IN_OFFSET =  rs.getInt("SETTLED_LOCK_IN_OFFSET");
     int SETTLED_OPTION_SEQ_NUM =  rs.getInt("SETTLED_OPTION_SEQ_NUM");
     int SETTLED_TERM_SEQ_NUM =  rs.getInt("SETTLED_TERM_SEQ_NUM");
     int SLLE_CONFIRMED_STATUS =  rs.getInt("SLLE_CONFIRMED_STATUS");
     int SLLE_DEPOSITED_STATUS =  rs.getInt("SLLE_DEPOSITED_STATUS");
     int SOFT_LOCK_KEY =  rs.getInt("SOFT_LOCK_KEY");
     int SOURCE_COMPLETENESS_STATUS =  rs.getInt("SOURCE_COMPLETENESS_STATUS");
     int STATUS =  rs.getInt("STATUS");
     int SUB_FUNCTION =  rs.getInt("SUB_FUNCTION");
     String SYS_ENTRY_DATE =  rs.getString("SYS_ENTRY_DATE");
     String TRADED_LOCK_IN_DATE =  rs.getString("TRADED_LOCK_IN_DATE");
     int TRADED_LOCK_IN_DATE_ATT_ID =  rs.getInt("TRADED_LOCK_IN_DATE_ATT_ID");
     int TRADED_LOCK_IN_OFFSET =  rs.getInt("TRADED_LOCK_IN_OFFSET");
     int TRADED_OPTION_SEQ_NUM =  rs.getInt("TRADED_OPTION_SEQ_NUM");
     int TRADED_TERM_SEQ_NUM =  rs.getInt("TRADED_TERM_SEQ_NUM");
     int TRADE_BLOCKING_STATUS =  rs.getInt("TRADE_BLOCKING_STATUS");
     String USER_ID =  rs.getString("USER_ID");
     int VOTING_FORM_COMPLETE_STATUS =  rs.getInt("VOTING_FORM_COMPLETE_STATUS");
     int VOTING_STATUS =  rs.getInt("VOTING_STATUS");

     
	  myWriter.write(ACTIVE_STATUS+","+APPROVAL_STATUS+","+ARCHIVAL_STATUS+","+ASSET_ID+","+ASSET_IDENTIFIERS+","+BUYA_CONFIRMED_STATUS+","+BUYA_DEPOSITED_STATUS+","+CA_ACCOUNT_REFERENCE+","+CA_REFERENCE+","+CA_SENDER_REFERENCE+","+CA_SOURCE_RULE+","+CLEANSE_BY_DATE+","+CLEANSING_RANK+","+CLEANSING_STATUS+","+CLOSED_DT+","+COMMON_GROUPING_ATT+","+COMMUNICATION_STATUS+","+COMPLETENESS_STATUS+","+CONTINUATION_INDICATOR+","+CRITICAL_DATE+","+DATA_SOURCE+","+DEFAULT_OPTION_STATUS+","+DEPOSITED_STATUS+","+DEPOSIT_CONFIRMED_STATUS+","+DETAIL_COMPLETENESS_STATUS+","+ELECTION_REC_FLAG+","+ELECTION_REC_STATUS+","+ELECTION_STATUS+","+ELGBLTY_IND+","+ELGBL_BAL_IND+","+ELIGIBLE_POSITIONS_REQ_STATUS+","+ENTITLEMENT_REC_FLAG+","+ENTITLEMENT_REC_STATUS+","+ENTITLEMENT_STATUS+","+ENTITY_TYPE+","+EVENT_FUNCTION+","+EVENT_NUM+","+EVENT_TYPE+","+EVT_CMPLTNS_STS+","+EVT_CONF_STS+","+FLOW_ID+","+FORECAST_CONFIRMATION_STRATEGY+","+FORECAST_STATUS+","+GOLDEN_RECORD_FLAG+","+HAS_NARRATIVE+","+HAS_OPTION+","+INBOX_ID+","+INTERNAL_DEADLINE_DATE+","+INTERNAL_DEADLINE_DISPLAY+","+INTERNAL_DEADLINE_FORMAT_TYPE+","+INTERNAL_DEADLINE_TIMEZONE+","+IS_LATEST_SUMMARY+","+IS_OUTCOME_BLOCKING_ACTIVE+","+IS_TRADE_BLOCKING_ACTIVE+","+LAST_ACTION_DATE+","+LAST_ACTION_ID+","+LAST_ACTION_OWNER+","+LINKED_EVENT_NUM+","+LISTING_ID+","+LOAD_FAILURE_CODE+","+LOAD_FAILURE_REVIEWED+","+MANDATORY_OPTIONS+","+MAND_VOLU_INDICATOR+","+MASTER_ID+","+MASTER_RECORD_LOCK+","+MINIMUM_SOURCE_STATUS+","+MIN_NO_OF_OPTIONS+","+NARRATIVE_LOCK_STATUS+","+NEXT_REVIEW_DATE+","+NOTE_ID+","+OFFEROR+","+OPTION_CLEANSING_STATUS+","+OPTION_COMPLETENESS_STATUS+","+OUTCOME_BLOCKING_STATUS+","+OVERALL_STATUS+","+PAGE_NUMBER+","+POSITION_REC_FLAG+","+POSITION_REC_STATUS+","+PREPARATION_DT+","+PRIORITY+","+PROCESSING_STATUS+","+PROCESSING_TYPE+","+READY_FOR_ARCHIVAL_DATE+","+READ_STATUS+","+RECONCILIATION_STATUS+","+RECORD_TYPE+","+REC_EVENT_CONFIG_ID+","+RESPONSIBLE_PARTY+","+RESP_PARTY_MANUAL_CHANGE+","+RVSL_RSN+","+SETTLED_LOCK_IN_DATE+","+SETTLED_LOCK_IN_DATE_ATT_ID+","+SETTLED_LOCK_IN_OFFSET+","+SETTLED_OPTION_SEQ_NUM+","+SETTLED_TERM_SEQ_NUM+","+SLLE_CONFIRMED_STATUS+","+SLLE_DEPOSITED_STATUS+","+SOFT_LOCK_KEY+","+SOURCE_COMPLETENESS_STATUS+","+STATUS+","+SUB_FUNCTION+","+SYS_ENTRY_DATE+","+TRADED_LOCK_IN_DATE+","+TRADED_LOCK_IN_DATE_ATT_ID+","+TRADED_LOCK_IN_OFFSET+","+TRADED_OPTION_SEQ_NUM+","+TRADED_TERM_SEQ_NUM+","+TRADE_BLOCKING_STATUS+","+USER_ID+","+VOTING_FORM_COMPLETE_STATUS+","+VOTING_STATUS);
	  myWriter.write("\n");

 
     
     System.out.println(ACTIVE_STATUS+","+APPROVAL_STATUS+","+ARCHIVAL_STATUS+","+ASSET_ID+","+ASSET_IDENTIFIERS+","+BUYA_CONFIRMED_STATUS+","+BUYA_DEPOSITED_STATUS+","+CA_ACCOUNT_REFERENCE+","+CA_REFERENCE+","+CA_SENDER_REFERENCE+","+CA_SOURCE_RULE+","+CLEANSE_BY_DATE+","+CLEANSING_RANK+","+CLEANSING_STATUS+","+CLOSED_DT+","+COMMON_GROUPING_ATT+","+COMMUNICATION_STATUS+","+COMPLETENESS_STATUS+","+CONTINUATION_INDICATOR+","+CRITICAL_DATE+","+DATA_SOURCE+","+DEFAULT_OPTION_STATUS+","+DEPOSITED_STATUS+","+DEPOSIT_CONFIRMED_STATUS+","+DETAIL_COMPLETENESS_STATUS+","+ELECTION_REC_FLAG+","+ELECTION_REC_STATUS+","+ELECTION_STATUS+","+ELGBLTY_IND+","+ELGBL_BAL_IND+","+ELIGIBLE_POSITIONS_REQ_STATUS+","+ENTITLEMENT_REC_FLAG+","+ENTITLEMENT_REC_STATUS+","+ENTITLEMENT_STATUS+","+ENTITY_TYPE+","+EVENT_FUNCTION+","+EVENT_NUM+","+EVENT_TYPE+","+EVT_CMPLTNS_STS+","+EVT_CONF_STS+","+FLOW_ID+","+FORECAST_CONFIRMATION_STRATEGY+","+FORECAST_STATUS+","+GOLDEN_RECORD_FLAG+","+HAS_NARRATIVE+","+HAS_OPTION+","+INBOX_ID+","+INTERNAL_DEADLINE_DATE+","+INTERNAL_DEADLINE_DISPLAY+","+INTERNAL_DEADLINE_FORMAT_TYPE+","+INTERNAL_DEADLINE_TIMEZONE+","+IS_LATEST_SUMMARY+","+IS_OUTCOME_BLOCKING_ACTIVE+","+IS_TRADE_BLOCKING_ACTIVE+","+LAST_ACTION_DATE+","+LAST_ACTION_ID+","+LAST_ACTION_OWNER+","+LINKED_EVENT_NUM+","+LISTING_ID+","+LOAD_FAILURE_CODE+","+LOAD_FAILURE_REVIEWED+","+MANDATORY_OPTIONS+","+MAND_VOLU_INDICATOR+","+MASTER_ID+","+MASTER_RECORD_LOCK+","+MINIMUM_SOURCE_STATUS+","+MIN_NO_OF_OPTIONS+","+NARRATIVE_LOCK_STATUS+","+NEXT_REVIEW_DATE+","+NOTE_ID+","+OFFEROR+","+OPTION_CLEANSING_STATUS+","+OPTION_COMPLETENESS_STATUS+","+OUTCOME_BLOCKING_STATUS+","+OVERALL_STATUS+","+PAGE_NUMBER+","+POSITION_REC_FLAG+","+POSITION_REC_STATUS+","+PREPARATION_DT+","+PRIORITY+","+PROCESSING_STATUS+","+PROCESSING_TYPE+","+READY_FOR_ARCHIVAL_DATE+","+READ_STATUS+","+RECONCILIATION_STATUS+","+RECORD_TYPE+","+REC_EVENT_CONFIG_ID+","+RESPONSIBLE_PARTY+","+RESP_PARTY_MANUAL_CHANGE+","+RVSL_RSN+","+SETTLED_LOCK_IN_DATE+","+SETTLED_LOCK_IN_DATE_ATT_ID+","+SETTLED_LOCK_IN_OFFSET+","+SETTLED_OPTION_SEQ_NUM+","+SETTLED_TERM_SEQ_NUM+","+SLLE_CONFIRMED_STATUS+","+SLLE_DEPOSITED_STATUS+","+SOFT_LOCK_KEY+","+SOURCE_COMPLETENESS_STATUS+","+STATUS+","+SUB_FUNCTION+","+SYS_ENTRY_DATE+","+TRADED_LOCK_IN_DATE+","+TRADED_LOCK_IN_DATE_ATT_ID+","+TRADED_LOCK_IN_OFFSET+","+TRADED_OPTION_SEQ_NUM+","+TRADED_TERM_SEQ_NUM+","+TRADE_BLOCKING_STATUS+","+USER_ID+","+VOTING_FORM_COMPLETE_STATUS+","+VOTING_STATUS);

      }
      rs.close();
      stmt.close();
      con.close();
      myWriter.close();
      System.out.println("Successfully executed");
	}
}
