package packageCA_Event_Option_Price;

import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.io.IOException;  // Import the IOException class to handle errors


public class ClassCA_Event_Option_Price {

	public  void methodCA_EVENT_optionPrice(String Arg_DB_endpoint,String Arg_port,String Arg_DB_SID,String Arg_DB_uname,String Arg_DB_password,String Arg_Event_num) throws SQLException, IOException{
		
		
		
		String DB_endpoint= Arg_DB_endpoint;
	     String port= Arg_port;
	     String DB_SID= Arg_DB_SID;
	     String DB_uname= Arg_DB_uname;
	     String DB_password= Arg_DB_password;
	     String Event_num = Arg_Event_num;
	     
	     String sql   = "select  ACTIVE_STATUS,	ARCHIVAL_STATUS,	CINL_AMOUNT_TYPE,	CINL_DISPLAY,	CINL_FIRST_CURRENCY,	CINL_FORMAT_TYPE,	CINL_PERCENTAGE_TYPE_CODE,	CINL_PRICE,	CINL_PRICE_CODE,	ENTITY_TYPE,	EVENT_NUM,	EXER_AMOUNT_TYPE,	EXER_DISPLAY,	EXER_FIRST_CURRENCY,	EXER_FORMAT_TYPE,	EXER_INDEX_POINTS,	EXER_PERCENTAGE_TYPE_CODE,	EXER_PRICE,	EXER_PRICE_CODE,	FLOW_ID,	INBOX_ID,	INDC_AMOUNT_TYPE,	INDC_DISPLAY,	INDC_FIRST_CURRENCY,	INDC_FORMAT_TYPE,	INDC_PERCENTAGE_TYPE_CODE,	INDC_PRICE,	INDC_PRICE_CODE,	ISSU_AMOUNT_TYPE,	ISSU_DISPLAY,	ISSU_FIRST_CURRENCY,	ISSU_FORMAT_TYPE,	ISSU_PERCENTAGE_TYPE_CODE,	ISSU_PRICE,	ISSU_PRICE_CODE,	MACI_AMOUNT_TYPE,	MACI_DISPLAY,	MACI_FIRST_CURRENCY,	MACI_FORMAT_TYPE,	MACI_PRICE,	MACI_PRICE_CODE,	MAXP_AMOUNT_TYPE,	MAXP_DISPLAY,	MAXP_FIRST_CURRENCY,	MAXP_FORMAT_TYPE,	MAXP_PERCENTAGE_TYPE_CODE,	MAXP_PRICE,	MICI_AMOUNT_TYPE,	MICI_DISPLAY,	MICI_FIRST_CURRENCY,	MICI_FORMAT_TYPE,	MICI_PRICE,	MICI_PRICE_CODE,	MINP_AMOUNT_TYPE,	MINP_DISPLAY,	MINP_FIRST_CURRENCY,	MINP_FORMAT_TYPE,	MINP_PERCENTAGE_TYPE_CODE,	MINP_PRICE,	MMCI_AMOUNT_TYPE,	MMCI_DISPLAY,	MMCI_FIRST_CURRENCY,	MMCI_FORMAT_TYPE,	MMCI_PRICE,	MMCI_PRICE_CODE,	MRKT_AMOUNT_TYPE,	MRKT_DISPLAY,	MRKT_FIRST_CURRENCY,	MRKT_FORMAT_TYPE,	MRKT_PERCENTAGE_TYPE_CODE,	MRKT_PRICE,	MRKT_PRICE_CODE,	OFFR_AMOUNT_TYPE,	OFFR_DISPLAY,	OFFR_FIRST_AMOUNT,	OFFR_FIRST_CURRENCY,	OFFR_FORMAT_TYPE,	OFFR_PERCENTAGE_TYPE_CODE,	OFFR_PRICE,	OFFR_PRICE_CODE,	OFFR_QUANTITY,	OFFR_QUANTITY_TYPE,	OFFR_SECOND_AMOUNT,	OFFR_SECOND_CURRENCY,	OPTION_SEQUENCE_NUM,	OSUB_AMOUNT_TYPE,	OSUB_DISPLAY,	OSUB_FIRST_CURRENCY,	OSUB_FORMAT_TYPE,	OSUB_PERCENTAGE_TYPE_CODE,	OSUB_PRICE,	OSUB_PRICE_CODE,	OVERALL_STATUS,	PRIORITY,	PRPP_AMOUNT_TYPE,	PRPP_DISPLAY,	PRPP_FIRST_CURRENCY,	PRPP_FORMAT_TYPE,	PRPP_PERCENTAGE_TYPE_CODE,	PRPP_PRICE,	PRPP_PRICE_CODE,	READY_FOR_ARCHIVAL_DATE,	SOFT_LOCK_KEY,	SYS_ENTRY_DATE,	TDMT_AMOUNT_TYPE,	TDMT_DISPLAY,	TDMT_FIRST_CURRENCY,	TDMT_FORMAT_TYPE,	TDMT_PRICE from CA_EVENT_OPTION_PRICE where event_num in (select event_num from ca_Event where master_id in ( Select master_id from ca_event where event_num='"+Event_num+"'))" ;
	     
	     
	     
	     // Get SQL from the flat file named "sqlfile"
	     System.out.println(sql);
	       
	     try {
	     	Class.forName("oracle.jdbc.driver.OracleDriver");
			} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			} 
	     
	     FileWriter myWriter;
			
			myWriter = new FileWriter(System.getProperty("user.dir")+"\\"+Event_num+"CA_Event_Option_Price.csv");
			
			myWriter.write("ACTIVE_STATUS,	ARCHIVAL_STATUS,	CINL_AMOUNT_TYPE,	CINL_DISPLAY,	CINL_FIRST_CURRENCY,	CINL_FORMAT_TYPE,	CINL_PERCENTAGE_TYPE_CODE,	CINL_PRICE,	CINL_PRICE_CODE,	ENTITY_TYPE,	EVENT_NUM,	EXER_AMOUNT_TYPE,	EXER_DISPLAY,	EXER_FIRST_CURRENCY,	EXER_FORMAT_TYPE,	EXER_INDEX_POINTS,	EXER_PERCENTAGE_TYPE_CODE,	EXER_PRICE,	EXER_PRICE_CODE,	FLOW_ID,	INBOX_ID,	INDC_AMOUNT_TYPE,	INDC_DISPLAY,	INDC_FIRST_CURRENCY,	INDC_FORMAT_TYPE,	INDC_PERCENTAGE_TYPE_CODE,	INDC_PRICE,	INDC_PRICE_CODE,	ISSU_AMOUNT_TYPE,	ISSU_DISPLAY,	ISSU_FIRST_CURRENCY,	ISSU_FORMAT_TYPE,	ISSU_PERCENTAGE_TYPE_CODE,	ISSU_PRICE,	ISSU_PRICE_CODE,	MACI_AMOUNT_TYPE,	MACI_DISPLAY,	MACI_FIRST_CURRENCY,	MACI_FORMAT_TYPE,	MACI_PRICE,	MACI_PRICE_CODE,	MAXP_AMOUNT_TYPE,	MAXP_DISPLAY,	MAXP_FIRST_CURRENCY,	MAXP_FORMAT_TYPE,	MAXP_PERCENTAGE_TYPE_CODE,	MAXP_PRICE,	MICI_AMOUNT_TYPE,	MICI_DISPLAY,	MICI_FIRST_CURRENCY,	MICI_FORMAT_TYPE,	MICI_PRICE,	MICI_PRICE_CODE,	MINP_AMOUNT_TYPE,	MINP_DISPLAY,	MINP_FIRST_CURRENCY,	MINP_FORMAT_TYPE,	MINP_PERCENTAGE_TYPE_CODE,	MINP_PRICE,	MMCI_AMOUNT_TYPE,	MMCI_DISPLAY,	MMCI_FIRST_CURRENCY,	MMCI_FORMAT_TYPE,	MMCI_PRICE,	MMCI_PRICE_CODE,	MRKT_AMOUNT_TYPE,	MRKT_DISPLAY,	MRKT_FIRST_CURRENCY,	MRKT_FORMAT_TYPE,	MRKT_PERCENTAGE_TYPE_CODE,	MRKT_PRICE,	MRKT_PRICE_CODE,	OFFR_AMOUNT_TYPE,	OFFR_DISPLAY,	OFFR_FIRST_AMOUNT,	OFFR_FIRST_CURRENCY,	OFFR_FORMAT_TYPE,	OFFR_PERCENTAGE_TYPE_CODE,	OFFR_PRICE,	OFFR_PRICE_CODE,	OFFR_QUANTITY,	OFFR_QUANTITY_TYPE,	OFFR_SECOND_AMOUNT,	OFFR_SECOND_CURRENCY,	OPTION_SEQUENCE_NUM,	OSUB_AMOUNT_TYPE,	OSUB_DISPLAY,	OSUB_FIRST_CURRENCY,	OSUB_FORMAT_TYPE,	OSUB_PERCENTAGE_TYPE_CODE,	OSUB_PRICE,	OSUB_PRICE_CODE,	OVERALL_STATUS,	PRIORITY,	PRPP_AMOUNT_TYPE,	PRPP_DISPLAY,	PRPP_FIRST_CURRENCY,	PRPP_FORMAT_TYPE,	PRPP_PERCENTAGE_TYPE_CODE,	PRPP_PRICE,	PRPP_PRICE_CODE,	READY_FOR_ARCHIVAL_DATE,	SOFT_LOCK_KEY,	SYS_ENTRY_DATE,	TDMT_AMOUNT_TYPE,	TDMT_DISPLAY,	TDMT_FIRST_CURRENCY,	TDMT_FORMAT_TYPE,	TDMT_PRICE \n");
			
	     Connection con = DriverManager.getConnection("jdbc:oracle:thin:@//"+DB_endpoint+":"+port+"/"+DB_SID+"", ""+DB_uname+"", ""+DB_password+""); 
	     Statement stmt = con.createStatement(); 
	     ResultSet rs = stmt.executeQuery(sql);
	    
	     while(rs.next()){
	         //Retrieve by column name
	     
	    	 int ACTIVE_STATUS =  rs.getInt("ACTIVE_STATUS");
	    	 int ARCHIVAL_STATUS =  rs.getInt("ARCHIVAL_STATUS");
	    	 int CINL_AMOUNT_TYPE =  rs.getInt("CINL_AMOUNT_TYPE");
	    	 String CINL_DISPLAY =  rs.getString("CINL_DISPLAY");
	    	 int CINL_FIRST_CURRENCY =  rs.getInt("CINL_FIRST_CURRENCY");
	    	 int CINL_FORMAT_TYPE =  rs.getInt("CINL_FORMAT_TYPE");
	    	 int CINL_PERCENTAGE_TYPE_CODE =  rs.getInt("CINL_PERCENTAGE_TYPE_CODE");
	    	 int CINL_PRICE =  rs.getInt("CINL_PRICE");
	    	 int CINL_PRICE_CODE =  rs.getInt("CINL_PRICE_CODE");
	    	 int ENTITY_TYPE =  rs.getInt("ENTITY_TYPE");
	    	 int EVENT_NUM =  rs.getInt("EVENT_NUM");
	    	 int EXER_AMOUNT_TYPE =  rs.getInt("EXER_AMOUNT_TYPE");
	    	 String EXER_DISPLAY =  rs.getString("EXER_DISPLAY");
	    	 int EXER_FIRST_CURRENCY =  rs.getInt("EXER_FIRST_CURRENCY");
	    	 int EXER_FORMAT_TYPE =  rs.getInt("EXER_FORMAT_TYPE");
	    	 int EXER_INDEX_POINTS =  rs.getInt("EXER_INDEX_POINTS");
	    	 int EXER_PERCENTAGE_TYPE_CODE =  rs.getInt("EXER_PERCENTAGE_TYPE_CODE");
	    	 int EXER_PRICE =  rs.getInt("EXER_PRICE");
	    	 int EXER_PRICE_CODE =  rs.getInt("EXER_PRICE_CODE");
	    	 int FLOW_ID =  rs.getInt("FLOW_ID");
	    	 int INBOX_ID =  rs.getInt("INBOX_ID");
	    	 int INDC_AMOUNT_TYPE =  rs.getInt("INDC_AMOUNT_TYPE");
	    	 String INDC_DISPLAY =  rs.getString("INDC_DISPLAY");
	    	 int INDC_FIRST_CURRENCY =  rs.getInt("INDC_FIRST_CURRENCY");
	    	 int INDC_FORMAT_TYPE =  rs.getInt("INDC_FORMAT_TYPE");
	    	 int INDC_PERCENTAGE_TYPE_CODE =  rs.getInt("INDC_PERCENTAGE_TYPE_CODE");
	    	 int INDC_PRICE =  rs.getInt("INDC_PRICE");
	    	 int INDC_PRICE_CODE =  rs.getInt("INDC_PRICE_CODE");
	    	 int ISSU_AMOUNT_TYPE =  rs.getInt("ISSU_AMOUNT_TYPE");
	    	 String ISSU_DISPLAY =  rs.getString("ISSU_DISPLAY");
	    	 int ISSU_FIRST_CURRENCY =  rs.getInt("ISSU_FIRST_CURRENCY");
	    	 int ISSU_FORMAT_TYPE =  rs.getInt("ISSU_FORMAT_TYPE");
	    	 int ISSU_PERCENTAGE_TYPE_CODE =  rs.getInt("ISSU_PERCENTAGE_TYPE_CODE");
	    	 int ISSU_PRICE =  rs.getInt("ISSU_PRICE");
	    	 int ISSU_PRICE_CODE =  rs.getInt("ISSU_PRICE_CODE");
	    	 int MACI_AMOUNT_TYPE =  rs.getInt("MACI_AMOUNT_TYPE");
	    	 String MACI_DISPLAY =  rs.getString("MACI_DISPLAY");
	    	 int MACI_FIRST_CURRENCY =  rs.getInt("MACI_FIRST_CURRENCY");
	    	 int MACI_FORMAT_TYPE =  rs.getInt("MACI_FORMAT_TYPE");
	    	 int MACI_PRICE =  rs.getInt("MACI_PRICE");
	    	 int MACI_PRICE_CODE =  rs.getInt("MACI_PRICE_CODE");
	    	 int MAXP_AMOUNT_TYPE =  rs.getInt("MAXP_AMOUNT_TYPE");
	    	 String MAXP_DISPLAY =  rs.getString("MAXP_DISPLAY");
	    	 int MAXP_FIRST_CURRENCY =  rs.getInt("MAXP_FIRST_CURRENCY");
	    	 int MAXP_FORMAT_TYPE =  rs.getInt("MAXP_FORMAT_TYPE");
	    	 int MAXP_PERCENTAGE_TYPE_CODE =  rs.getInt("MAXP_PERCENTAGE_TYPE_CODE");
	    	 int MAXP_PRICE =  rs.getInt("MAXP_PRICE");
	    	 int MICI_AMOUNT_TYPE =  rs.getInt("MICI_AMOUNT_TYPE");
	    	 String MICI_DISPLAY =  rs.getString("MICI_DISPLAY");
	    	 int MICI_FIRST_CURRENCY =  rs.getInt("MICI_FIRST_CURRENCY");
	    	 int MICI_FORMAT_TYPE =  rs.getInt("MICI_FORMAT_TYPE");
	    	 int MICI_PRICE =  rs.getInt("MICI_PRICE");
	    	 int MICI_PRICE_CODE =  rs.getInt("MICI_PRICE_CODE");
	    	 int MINP_AMOUNT_TYPE =  rs.getInt("MINP_AMOUNT_TYPE");
	    	 String MINP_DISPLAY =  rs.getString("MINP_DISPLAY");
	    	 int MINP_FIRST_CURRENCY =  rs.getInt("MINP_FIRST_CURRENCY");
	    	 int MINP_FORMAT_TYPE =  rs.getInt("MINP_FORMAT_TYPE");
	    	 int MINP_PERCENTAGE_TYPE_CODE =  rs.getInt("MINP_PERCENTAGE_TYPE_CODE");
	    	 int MINP_PRICE =  rs.getInt("MINP_PRICE");
	    	 int MMCI_AMOUNT_TYPE =  rs.getInt("MMCI_AMOUNT_TYPE");
	    	 String MMCI_DISPLAY =  rs.getString("MMCI_DISPLAY");
	    	 int MMCI_FIRST_CURRENCY =  rs.getInt("MMCI_FIRST_CURRENCY");
	    	 int MMCI_FORMAT_TYPE =  rs.getInt("MMCI_FORMAT_TYPE");
	    	 int MMCI_PRICE =  rs.getInt("MMCI_PRICE");
	    	 int MMCI_PRICE_CODE =  rs.getInt("MMCI_PRICE_CODE");
	    	 int MRKT_AMOUNT_TYPE =  rs.getInt("MRKT_AMOUNT_TYPE");
	    	 String MRKT_DISPLAY =  rs.getString("MRKT_DISPLAY");
	    	 int MRKT_FIRST_CURRENCY =  rs.getInt("MRKT_FIRST_CURRENCY");
	    	 int MRKT_FORMAT_TYPE =  rs.getInt("MRKT_FORMAT_TYPE");
	    	 int MRKT_PERCENTAGE_TYPE_CODE =  rs.getInt("MRKT_PERCENTAGE_TYPE_CODE");
	    	 int MRKT_PRICE =  rs.getInt("MRKT_PRICE");
	    	 int MRKT_PRICE_CODE =  rs.getInt("MRKT_PRICE_CODE");
	    	 int OFFR_AMOUNT_TYPE =  rs.getInt("OFFR_AMOUNT_TYPE");
	    	 String OFFR_DISPLAY =  rs.getString("OFFR_DISPLAY");
	    	 int OFFR_FIRST_AMOUNT =  rs.getInt("OFFR_FIRST_AMOUNT");
	    	 int OFFR_FIRST_CURRENCY =  rs.getInt("OFFR_FIRST_CURRENCY");
	    	 int OFFR_FORMAT_TYPE =  rs.getInt("OFFR_FORMAT_TYPE");
	    	 int OFFR_PERCENTAGE_TYPE_CODE =  rs.getInt("OFFR_PERCENTAGE_TYPE_CODE");
	    	 int OFFR_PRICE =  rs.getInt("OFFR_PRICE");
	    	 int OFFR_PRICE_CODE =  rs.getInt("OFFR_PRICE_CODE");
	    	 int OFFR_QUANTITY =  rs.getInt("OFFR_QUANTITY");
	    	 int OFFR_QUANTITY_TYPE =  rs.getInt("OFFR_QUANTITY_TYPE");
	    	 int OFFR_SECOND_AMOUNT =  rs.getInt("OFFR_SECOND_AMOUNT");
	    	 int OFFR_SECOND_CURRENCY =  rs.getInt("OFFR_SECOND_CURRENCY");
	    	 int OPTION_SEQUENCE_NUM =  rs.getInt("OPTION_SEQUENCE_NUM");
	    	 int OSUB_AMOUNT_TYPE =  rs.getInt("OSUB_AMOUNT_TYPE");
	    	 String OSUB_DISPLAY =  rs.getString("OSUB_DISPLAY");
	    	 int OSUB_FIRST_CURRENCY =  rs.getInt("OSUB_FIRST_CURRENCY");
	    	 int OSUB_FORMAT_TYPE =  rs.getInt("OSUB_FORMAT_TYPE");
	    	 int OSUB_PERCENTAGE_TYPE_CODE =  rs.getInt("OSUB_PERCENTAGE_TYPE_CODE");
	    	 int OSUB_PRICE =  rs.getInt("OSUB_PRICE");
	    	 int OSUB_PRICE_CODE =  rs.getInt("OSUB_PRICE_CODE");
	    	 int OVERALL_STATUS =  rs.getInt("OVERALL_STATUS");
	    	 int PRIORITY =  rs.getInt("PRIORITY");
	    	 int PRPP_AMOUNT_TYPE =  rs.getInt("PRPP_AMOUNT_TYPE");
	    	 String PRPP_DISPLAY =  rs.getString("PRPP_DISPLAY");
	    	 int PRPP_FIRST_CURRENCY =  rs.getInt("PRPP_FIRST_CURRENCY");
	    	 int PRPP_FORMAT_TYPE =  rs.getInt("PRPP_FORMAT_TYPE");
	    	 int PRPP_PERCENTAGE_TYPE_CODE =  rs.getInt("PRPP_PERCENTAGE_TYPE_CODE");
	    	 int PRPP_PRICE =  rs.getInt("PRPP_PRICE");
	    	 int PRPP_PRICE_CODE =  rs.getInt("PRPP_PRICE_CODE");
	    	 String READY_FOR_ARCHIVAL_DATE =  rs.getString("READY_FOR_ARCHIVAL_DATE");
	    	 int SOFT_LOCK_KEY =  rs.getInt("SOFT_LOCK_KEY");
	    	 String SYS_ENTRY_DATE =  rs.getString("SYS_ENTRY_DATE");
	    	 int TDMT_AMOUNT_TYPE =  rs.getInt("TDMT_AMOUNT_TYPE");
	    	 String TDMT_DISPLAY =  rs.getString("TDMT_DISPLAY");
	    	 int TDMT_FIRST_CURRENCY =  rs.getInt("TDMT_FIRST_CURRENCY");
	    	 int TDMT_FORMAT_TYPE =  rs.getInt("TDMT_FORMAT_TYPE");
	    	 int TDMT_PRICE =  rs.getInt("TDMT_PRICE");

		  myWriter.write(ACTIVE_STATUS+","	+ARCHIVAL_STATUS+","	+CINL_AMOUNT_TYPE+","	+CINL_DISPLAY+","	+CINL_FIRST_CURRENCY+","	+CINL_FORMAT_TYPE+","	+CINL_PERCENTAGE_TYPE_CODE+","	+CINL_PRICE+","	+CINL_PRICE_CODE+","	+ENTITY_TYPE+","	+EVENT_NUM+","	+EXER_AMOUNT_TYPE+","	+EXER_DISPLAY+","	+EXER_FIRST_CURRENCY+","	+EXER_FORMAT_TYPE+","	+EXER_INDEX_POINTS+","	+EXER_PERCENTAGE_TYPE_CODE+","	+EXER_PRICE+","	+EXER_PRICE_CODE+","	+FLOW_ID+","	+INBOX_ID+","	+INDC_AMOUNT_TYPE+","	+INDC_DISPLAY+","	+INDC_FIRST_CURRENCY+","	+INDC_FORMAT_TYPE+","	+INDC_PERCENTAGE_TYPE_CODE+","	+INDC_PRICE+","	+INDC_PRICE_CODE+","	+ISSU_AMOUNT_TYPE+","	+ISSU_DISPLAY+","	+ISSU_FIRST_CURRENCY+","	+ISSU_FORMAT_TYPE+","	+ISSU_PERCENTAGE_TYPE_CODE+","	+ISSU_PRICE+","	+ISSU_PRICE_CODE+","	+MACI_AMOUNT_TYPE+","	+MACI_DISPLAY+","	+MACI_FIRST_CURRENCY+","	+MACI_FORMAT_TYPE+","	+MACI_PRICE+","	+MACI_PRICE_CODE+","	+MAXP_AMOUNT_TYPE+","	+MAXP_DISPLAY+","	+MAXP_FIRST_CURRENCY+","	+MAXP_FORMAT_TYPE+","	+MAXP_PERCENTAGE_TYPE_CODE+","	+MAXP_PRICE+","	+MICI_AMOUNT_TYPE+","	+MICI_DISPLAY+","	+MICI_FIRST_CURRENCY+","	+MICI_FORMAT_TYPE+","	+MICI_PRICE+","	+MICI_PRICE_CODE+","	+MINP_AMOUNT_TYPE+","	+MINP_DISPLAY+","	+MINP_FIRST_CURRENCY+","	+MINP_FORMAT_TYPE+","	+MINP_PERCENTAGE_TYPE_CODE+","	+MINP_PRICE+","	+MMCI_AMOUNT_TYPE+","	+MMCI_DISPLAY+","	+MMCI_FIRST_CURRENCY+","	+MMCI_FORMAT_TYPE+","	+MMCI_PRICE+","	+MMCI_PRICE_CODE+","	+MRKT_AMOUNT_TYPE+","	+MRKT_DISPLAY+","	+MRKT_FIRST_CURRENCY+","	+MRKT_FORMAT_TYPE+","	+MRKT_PERCENTAGE_TYPE_CODE+","	+MRKT_PRICE+","	+MRKT_PRICE_CODE+","	+OFFR_AMOUNT_TYPE+","	+OFFR_DISPLAY+","	+OFFR_FIRST_AMOUNT+","	+OFFR_FIRST_CURRENCY+","	+OFFR_FORMAT_TYPE+","	+OFFR_PERCENTAGE_TYPE_CODE+","	+OFFR_PRICE+","	+OFFR_PRICE_CODE+","	+OFFR_QUANTITY+","	+OFFR_QUANTITY_TYPE+","	+OFFR_SECOND_AMOUNT+","	+OFFR_SECOND_CURRENCY+","	+OPTION_SEQUENCE_NUM+","	+OSUB_AMOUNT_TYPE+","	+OSUB_DISPLAY+","	+OSUB_FIRST_CURRENCY+","	+OSUB_FORMAT_TYPE+","	+OSUB_PERCENTAGE_TYPE_CODE+","	+OSUB_PRICE+","	+OSUB_PRICE_CODE+","	+OVERALL_STATUS+","	+PRIORITY+","	+PRPP_AMOUNT_TYPE+","	+PRPP_DISPLAY+","	+PRPP_FIRST_CURRENCY+","	+PRPP_FORMAT_TYPE+","	+PRPP_PERCENTAGE_TYPE_CODE+","	+PRPP_PRICE+","	+PRPP_PRICE_CODE+","	+READY_FOR_ARCHIVAL_DATE+","	+SOFT_LOCK_KEY+","	+SYS_ENTRY_DATE+","	+TDMT_AMOUNT_TYPE+","	+TDMT_DISPLAY+","	+TDMT_FIRST_CURRENCY+","	+TDMT_FORMAT_TYPE+","	+TDMT_PRICE);
		  myWriter.write("\n");

	 
	     
	     System.out.println(ACTIVE_STATUS+","	+ARCHIVAL_STATUS+","	+CINL_AMOUNT_TYPE+","	+CINL_DISPLAY+","	+CINL_FIRST_CURRENCY+","	+CINL_FORMAT_TYPE+","	+CINL_PERCENTAGE_TYPE_CODE+","	+CINL_PRICE+","	+CINL_PRICE_CODE+","	+ENTITY_TYPE+","	+EVENT_NUM+","	+EXER_AMOUNT_TYPE+","	+EXER_DISPLAY+","	+EXER_FIRST_CURRENCY+","	+EXER_FORMAT_TYPE+","	+EXER_INDEX_POINTS+","	+EXER_PERCENTAGE_TYPE_CODE+","	+EXER_PRICE+","	+EXER_PRICE_CODE+","	+FLOW_ID+","	+INBOX_ID+","	+INDC_AMOUNT_TYPE+","	+INDC_DISPLAY+","	+INDC_FIRST_CURRENCY+","	+INDC_FORMAT_TYPE+","	+INDC_PERCENTAGE_TYPE_CODE+","	+INDC_PRICE+","	+INDC_PRICE_CODE+","	+ISSU_AMOUNT_TYPE+","	+ISSU_DISPLAY+","	+ISSU_FIRST_CURRENCY+","	+ISSU_FORMAT_TYPE+","	+ISSU_PERCENTAGE_TYPE_CODE+","	+ISSU_PRICE+","	+ISSU_PRICE_CODE+","	+MACI_AMOUNT_TYPE+","	+MACI_DISPLAY+","	+MACI_FIRST_CURRENCY+","	+MACI_FORMAT_TYPE+","	+MACI_PRICE+","	+MACI_PRICE_CODE+","	+MAXP_AMOUNT_TYPE+","	+MAXP_DISPLAY+","	+MAXP_FIRST_CURRENCY+","	+MAXP_FORMAT_TYPE+","	+MAXP_PERCENTAGE_TYPE_CODE+","	+MAXP_PRICE+","	+MICI_AMOUNT_TYPE+","	+MICI_DISPLAY+","	+MICI_FIRST_CURRENCY+","	+MICI_FORMAT_TYPE+","	+MICI_PRICE+","	+MICI_PRICE_CODE+","	+MINP_AMOUNT_TYPE+","	+MINP_DISPLAY+","	+MINP_FIRST_CURRENCY+","	+MINP_FORMAT_TYPE+","	+MINP_PERCENTAGE_TYPE_CODE+","	+MINP_PRICE+","	+MMCI_AMOUNT_TYPE+","	+MMCI_DISPLAY+","	+MMCI_FIRST_CURRENCY+","	+MMCI_FORMAT_TYPE+","	+MMCI_PRICE+","	+MMCI_PRICE_CODE+","	+MRKT_AMOUNT_TYPE+","	+MRKT_DISPLAY+","	+MRKT_FIRST_CURRENCY+","	+MRKT_FORMAT_TYPE+","	+MRKT_PERCENTAGE_TYPE_CODE+","	+MRKT_PRICE+","	+MRKT_PRICE_CODE+","	+OFFR_AMOUNT_TYPE+","	+OFFR_DISPLAY+","	+OFFR_FIRST_AMOUNT+","	+OFFR_FIRST_CURRENCY+","	+OFFR_FORMAT_TYPE+","	+OFFR_PERCENTAGE_TYPE_CODE+","	+OFFR_PRICE+","	+OFFR_PRICE_CODE+","	+OFFR_QUANTITY+","	+OFFR_QUANTITY_TYPE+","	+OFFR_SECOND_AMOUNT+","	+OFFR_SECOND_CURRENCY+","	+OPTION_SEQUENCE_NUM+","	+OSUB_AMOUNT_TYPE+","	+OSUB_DISPLAY+","	+OSUB_FIRST_CURRENCY+","	+OSUB_FORMAT_TYPE+","	+OSUB_PERCENTAGE_TYPE_CODE+","	+OSUB_PRICE+","	+OSUB_PRICE_CODE+","	+OVERALL_STATUS+","	+PRIORITY+","	+PRPP_AMOUNT_TYPE+","	+PRPP_DISPLAY+","	+PRPP_FIRST_CURRENCY+","	+PRPP_FORMAT_TYPE+","	+PRPP_PERCENTAGE_TYPE_CODE+","	+PRPP_PRICE+","	+PRPP_PRICE_CODE+","	+READY_FOR_ARCHIVAL_DATE+","	+SOFT_LOCK_KEY+","	+SYS_ENTRY_DATE+","	+TDMT_AMOUNT_TYPE+","	+TDMT_DISPLAY+","	+TDMT_FIRST_CURRENCY+","	+TDMT_FORMAT_TYPE+","	+TDMT_PRICE);

	      }
	      rs.close();
	      stmt.close();
	      con.close();
	      myWriter.close();
	      System.out.println("Successfully executed");
		}

}
